version: "3"
services:
  db.feature.ai:
    image: watchtek/pgvector:latest
    container_name: db.feature.ai
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWD}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - rag_network
networks:
  rag_network:
